### ISSUE TITLE
README says 2 weeks from completion, last commit 9 months ago

### ISSUE THREAD

**Issue by reedspool** [SonOfLilit/re2#6]
Where's re2 at? Discovered this code by Internetting and found these slides, which are great: http://www.slideshare.net/AurSaraf/re3-modern-regex-syntax-with-a-focus-on-adoption

**Comment by SonOfLilit** [comment]
I had some time to work on it between jobs and the time was up. I couldn't
get commitment from companies to use it when it's production-ready, which
was my criterion for spending more time on it.

**Comment by reedspool** [comment]
Pro's gotta eat. Thanks for the update.
